version: "3"
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 20s
      retries: 5
    volumes:
      - "rabbitmq_data:/data"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  user-service:
    build:
      context: ./services/user-service
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017
      - AMQP_URI=amqp://guest:guest@rabbitmq:5672
    depends_on:
      mongodb:
        condition: service_started
      rabbitmq:
        condition: service_healthy
        restart: true

  cat-service:
    build:
      context: ./services/cat-service
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017
      - AMQP_URI=amqp://guest:guest@rabbitmq:5672
    depends_on:
      mongodb:
        condition: service_started
      rabbitmq:
        condition: service_healthy
        restart: true

  notifications-service:
    build:
      context: ./services/notifications-service
    ports:
      - "3003:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017
      - AMQP_URI=amqp://guest:guest@rabbitmq:5672
    depends_on:
      mongodb:
        condition: service_started
      rabbitmq:
        condition: service_healthy
        restart: true
volumes:
  mongodb_data:
  rabbitmq_data:
